config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #下記で「root〜」を設定したので、「get 'messages/index'」は削除した（コードreviewでご指摘を受けて）。
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #応用カリNo89の実演にて、indexアクションのroutingを追記
  # root "messages#index"
  #応用カリNo91にて、rootパスではside-bar部分のみの表示とするため、groups#indexアクションのroutingに修正
  root "groups#index"

  #応用カリNo90の実演にて、editアクションとupdateアクションのroutingを追記
  #（rootパスは、前単元で上記のとおり記載済み）
  #応用カリNo109にて、indexアクションのroutingを追記
  resources :users, only: [:index, :edit, :update]

  #応用カリNo91にて、groupsコントローラーに対するnewアクションとcreateアクションのroutingを追記
  #グループ情報編集機能の実装につき、editアクションとupdateアクションのroutingを追記
  #さらに、トップ画面の実装につき、indexアクションのroutingを追記
  #さらに、messagesコントローラーに対してcreateアクションのroutingを追記し、indexはmessagesに再設定
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
    #応用No110にて、WebAPIとしたcontrollerでのアクションを実行する下記のroutingを追記
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord

  #応用カリNo91にて、テーブル間のassociationとvalidationの設定を追記
  #group_usersテーブルに対して1vs多のrelationを設定
  has_many :group_users
  #group_usersテーブルを介して、usersテーブルに対して1vs多のrelationを設定
  has_many :users, through: :group_users

  #応用カリNo92にて、messageテーブルに対して1vs多のrelationを設定
  has_many :messages

  #nameカラムについて、入力必須、重複NGの制約を設定
  validates :name, presence: true, uniqueness: true

  #応用カリNo97にて、テストコード実施時に無用の警告文の表示を回避できる記述（なくてもよい）
  validates :name, presence: true, uniqueness: {case_sensitive: true}

  #応用カリNo92、side-bar__contentに最新メッセージを表示する設定の実装にて、
  #最新メッセージを探索・判別するメソッドを新設
  def show_last_message
    if (last_message = messages.last).present?
      if last_message.content?
        last_message.content
      else
        '画像が投稿されています'
      end
    else
      'まだメッセージはありません。'
    end
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord

  #応用カリNo91にて、中間テーブルとして、usersとgroupsとに対するrelationを設定
  belongs_to :group
  belongs_to :user

end

app/models/message.rb
class Message < ApplicationRecord

  #応用カリNo92にて、messageデータに対してgroupとuserとのrelationを設定する
  #（group-messageは1vs多、user-messageも1vs多）
  belongs_to :group
  belongs_to :user

  #同時に、messageデータについて、contentカラムは入力必須とするvalid制約を追加
  validates :content, presence: true, unless: :image?

  #さらに、imageデータについて、uploaderの設定を追記
  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #応用カリNo90の実演にて、「name」カラムの追加に伴うvalidationを設定
  validates :name, presence: true, uniqueness: true

  #応用カリNo91にて、groupsテーブルの追加に伴うassociationを設定
  has_many :group_users
  has_many :groups, through: :group_users

  #応用カリNo92にて、messageテーブルに対して1vs多のrelationを設定
  has_many :messages

  #応用カリNo97にて、テストコード実施時に無用の警告文の表示を回避できる記述（なくてもよい）
  validates :name, presence: true, uniqueness: {case_sensitive: true}
  
end

app/controllers/api/messages_controller.rb
#応用No110にて、APIとしてのcontrollerとするため、このファイルを新設

class Api::MessagesController < ApplicationController  #既存の「MessagesController」と共存させるため、名前空間にて「Api::」を冠した。
  def index  #カリどおり、下記コードを追記してindexアクションを定義する
    # ルーティングでの設定によりparamsの中にgroup_idというキーでグループのidが入るので、これを元にDBからグループを取得する
    group = Group.find(params[:group_id])
    # ajaxで送られてくる最後のメッセージのid番号を変数に代入
    last_message_id = params[:id]
    # 取得したグループでのメッセージ達から、idがlast_message_idよりも新しい(大きい)メッセージ達のみを取得
    @messages = group.messages.includes(:user).where("id > ?", last_message_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  #応用カリNo90の実演にて、SignUp用のアクションを追記
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    #サインアップ時に入力された「name」キーの内容の保存を許可するアクション設定
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/groups_controller.rb
#応用カリNo91にて、グループ管理機能の実装でCを作成

class GroupsController < ApplicationController

  #rootパスに対する表示をmessages#indexとして進めてきたところを、
  #viewのデザインに入ってgroups#indexとすることに伴い、このcontrollerにindexアクションを追記
  def index
  end

  #グループの新規登録に必要となる「new」と「create」のアクションを定義
  def new
    #@groupに空のインスタンスを代入する（form_withで使用するためのインスタンス変数）
    @group = Group.new
    #インスタンス変数@groupに、ログインuserの情報を追加する
    @group.users << current_user
  end

  def create
    #送信データのparamsを確認するためのpry設定
    # binding.pry

    #新規グループの登録、保存動作の成否によって処理を分ける条件分岐
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  #グループ情報の編集に関するアクション
  def edit
    @group = Group.find(params[:id])
  end

  #グループ情報の編集後の、更新に関するアクション
  #さらに、redirect先の変更（messages_controllerの記述に合わせ、「group_messages_path(@group)」に変更）
  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      # redirect_to root_path, notice: 'グループを更新しました'
      redirect_to group_messages_path(@group), notice: 'グループを更新しました'
    else
      render :edit
    end
  end

  #ストロングパラメータの設定
  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

end

app/controllers/messages_controller.rb
#応用No92にて、メッセージ送信機能実装のためmessages_controllerを作成

class MessagesController < ApplicationController

  #下記set_groupの処理を行うbefore_actionを設定
  before_action :set_group

  #controller生成当初に記述されていた「index」アクションに、処理内容のコードを追記
  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  #応用No92にて、メッセージ送信機能実装のためmessagesに「create」アクションを追記（詳細内容は追って追記）
  #同単元にて、詳細な処理内容を下記コードのとおり追記
  def create
    @message = @group.messages.new(message_params)
    if @message.save
      #応用No108、「問題3」にて、createアクションの対応を分けるコードに書き換え
      respond_to do |format|
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #応用カリNo90にて、editアクションを追記
  def edit
  end

  #応用カリNo90にて、updateアクションを追記
  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  #応用カリNo109にて、indexアクションを追記
  def index
    #さらに、下記コードを追記
    return nil if params[:keyword] == ""
    @users = User.where(['name LIKE ?', "%#{params[:keyword]}%"] ).where.not(id: current_user.id).limit(10)
    respond_to do |format|
      # format.html  #「htmlをレスポンスとするコードを削除しても問題ないか」の動作確認で削除した
      format.json  #サーバーはJSON形式で値を返し、jbuilderファイルが読み込まれるように
    end
  end

  private

  #応用カリNo90にて、user情報のparams定義を追記
  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
-#応用カリNo91にて、エラーメッセージ表示用のviewを、部分templateで作成

= form_with model: group, local: true do |f|
  -# .SettingGroupForm__errors
  -#   %h2 10件のエラーが発生しました
  -#   %ul
  -#     %li nameを入力してください

  -#上記の固定表示メッセージに代え、エラー数をカウントして表示する下記コードに書き換え
  - if group.errors.any?
    .SettingGroupForm__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message

  .SettingGroupForm__field
    .SettingGroupForm__leftField
      = f.label :name, "グループ名", class: 'SettingGroupForm__label'
    .SettingGroupForm__rightField
      = f.text_field :name, class: 'SettingGroupForm__input', placeholder: 'グループ名を入力してください'

  -#上記コードで表示される「グループ名」と同じ要素構成とするため、「.SettingGroupForm__field〜」などの記述は同じ
  .SettingGroupForm__field
    .SettingGroupForm__leftField
      %label.SettingGroupForm__label チャットメンバーを追加
    .SettingGroupForm__rightField
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      -# = f.collection_check_boxes :user_ids, User.all, :id, :name
      -#応用カリNo109にて、インクリメンタルサーチ機能実装のため、上行を下行に書き換え
      .UserSearch
        %input#UserSearch__field.SettingGroupForm__input{placeholder: "追加したいユーザー名を入力してください", type: "text"}/
      #UserSearchResult
  -#応用カリNo109にて、インクリメンタルサーチ機能実装のため、下記コードを追記
  -#（上記コードで表示される「チャットメンバーを追加」と同じ要素構成とするため、「.SettingGroupForm__field〜」などの記述は同じ）
  .SettingGroupForm__field
    .SettingGroupForm__leftField
      = f.label :name, value: "チャットメンバー", class: "SettingGroupForm__label"
    .SettingGroupForm__rightField
      .ChatMembers
        -#応用No109にて、メンバー追加ボタンに対応するイベント、削除ボタンに対応するイベントのコードを追記
        -#class名「ChatMember」は、「Chat-Group-Member」に変えたので書き換え
        -# .ChatMember
        .Chat-Group-Member
          -# %p.ChatMember__name= current_user.name
          %p.Chat-Group-Member__name= current_user.name
          %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
        - group.users.each do |user|
          - if current_user.name != user.name
            -# .ChatMember
            .Chat-Group-Member
              -# %p.ChatMember__name
              %p.Chat-Group-Member__name
                = user.name
              -# .ChatMember__remove.ChatMember__button{"data-user-id": user.id, "data-user-name": user.name} 削除
              .Chat-Group-Member__remove.Chat-Group-Member__button{"data-user-id": user.id, "data-user-name": user.name} 削除
              %input{name: "group[user_ids][]", type:"hidden", value: user.id}
  
  / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .SettingGroupForm__field
    .SettingGroupForm__leftField
    .SettingGroupForm__rightField
      = f.submit class: 'SettingGroupForm__button'

app/views/groups/edit.html.haml
-#応用カリNo91にて、グループ情報の編集画面のviewファイルとして作成

-#仮表示の文字列
-# ＜チャットグループ編集＞

-#グループ情報の編集画面viewのコード
-# = form_with model: @group, local: true do |f|
-#   = f.text_field :name, class: "SettingGroupForm__input", placeholder: "グループ名を入力してください"
-#   = f.collection_check_boxes :user_ids, User.all, :id, :name
-#   = f.submit "Save", class: "SettingGroupForm__button"

-#応用カリNo91にて、部分templateでviewを表示するように変更することに伴い、下記コードに書き換え
.SettingGroupForm
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
-#応用カリNo91にて、rootパスでgroup#indexアクションにつなげる変更をしたことに伴い、
-#groups下にindex.html.hamlを新設するもの

.wrapper
  = render 'messages/side_bar'

app/views/groups/new.html.haml
-#応用カリNo91にて、グループの新規登録画面のviewファイルとして作成

-#仮表示の文字列
-# ＜新規チャットグループ＞

-#応用カリNo91にて、checkbox形式でのデータ保存機能の実装にて追記
-# = form_with model: @group, local: true do |f|
-#   = f.text_field :name, class: "SettingGroupForm__input", placeholder: "グループ名を入力してください"
-#   = f.collection_check_boxes :user_ids, User.all, :id, :name
-#   = f.submit "Save", class: "SettingGroupForm__button"

-#応用カリNo91にて、部分templateでviewを表示するように変更することに伴い、下記コードに書き換え
.SettingGroupForm
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }

app/views/layouts/_notifications.html.haml
-#応用カリNo90にて、フラッシュメッセージ表示機能のviewとして作成

.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    -#応用No108にて、JS使用のためコードを書き換え
    = javascript_include_tag 'application'
  %body
    -#応用No90にて、フラッシュメッセージ表示機能として「notifications」のviewを呼び出す設定を追記
    = render 'layouts/notifications'
    = yield

app/views/messages/_main_chat.html.haml
.main-chat
  .main-chat__header
    .main-chat__header__group
      -#応用カリNo92、グループ名と所属メンバーを表示する設定の実装にて、group-nameとmember-listの表示コードを書き換え
      .main-chat__header__group__group-name
        -# ぐでたまグループ
        = @group.name
      .main-chat__header__group__member-list
        -# Member : KBY
        Member :
        - @group.users.each do |user|
          = user.name
    -#さらに、Editボタンにグループ編集ページへのリンクを設定
    -# .main-chat__header__btn
    -#   = link_to '#', class: "main-chat__header__btn main-chat__header__btn--edit" do
    .main-chat__header__btn
      = link_to edit_group_path(@group.id), class: "main-chat__header__btn main-chat__header__btn--edit" do
        Edit

  -#応用カリNo92、グループにメッセージを表示する設定の実装にて、viewに機能を実装するため、コードを書き換え
  .main-chat__content
    -# .main-chat__content__message
    -#   .main-chat__content__message__info
    -#     .main-chat__content__message__info__name
    -#       GUDE
    -#     .main-chat__content__message__info__date
    -#       2020/07/07(TUE) 07:09:51
    -#   .main-chat__content__message__comment
    -#     ぐーでたまたま
    -# .main-chat__content__message
    -#   .main-chat__content__message__info
    -#     .main-chat__content__message__info__name
    -#       GUDE
    -#     .main-chat__content__message__info__date
    -#       2020/08/08(SAT) 07:09:51
    -#   .main-chat__content__message__comment
    -#     だりぃ

    -#カリ内容を参考に、部分templateを呼び出すコードを実装
    = render @messages

  -#応用カリNo92、メッセージ送信機能実装にて、viewに機能を実装するため、コードを書き換え
  .main-chat__footer
    -# %form.inputfield
    -#   .textfield
    -#     %input{type: "text", class: "textfield__text", placeholder: "type a message"}
    -#     %label{class: "textfield__image"}
    -#       = icon('far', 'image')
    -#       %input{type: "file", class: "textfield__image__file"}
    -#   %input{type: "submit", class: "send-btn", value: "Send"}

    -#カリ内容のコードを参考に、クラス名やネスト構成を調整して下記コードにて実装
    = form_with model: [@group, @message], html: {class: "form"}, local: true do |f|
      .form.textfield
        = f.text_field :content, class: 'textfield__text', placeholder: 'type a message'
        = f.label :image, class: 'textfield__image' do
          = icon('far', 'image', class: 'textfield__image__icon')
          = f.file_field :image, class: 'textfield__image__file'
      = f.submit 'Send', class: 'send-btn'

app/views/messages/_message.html.haml
-#応用カリN092にて、main-chat__contentのメッセージ表示機能の実装のため、viewファイルを新設

-#カリ内容のコードを参考に、クラス名やネスト構成を調整して下記コードにて実装
-#応用カリNo110にて、カスタムデータ属性なるHTMLタグの属性を用いてmessagesテーブルのid情報をHTMLに埋め込む
-#（下行の「{data: {〜」以降部分を追記）
.main-chat__content__message{data: {message: {id: message.id}}}
  .main-chat__content__message__info
    .main-chat__content__message__info__name
      = message.user.name
    .main-chat__content__message__info__date
      = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
  .main-chat__content__message__comment
    - if message.content.present?
      %p.main-chat__content__message__comment
        = message.content
    = image_tag message.image.url, class: 'Message__image' if message.image.present?

-# .MessageBox
-#   .MessageInfo
-#     .MessageInfo__userName
-#       = message.user.name
-#     .MessageInfo__date
-#       = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
-#   .Message
-#     - if message.content.present?
-#       %p.Message__content
-#         = message.content
-#     = image_tag message.image.url, class: 'Message__image' if message.image.present?

app/views/messages/_side_bar.html.haml
.side-bar
  .side-bar__header
    .side-bar__header__box
      .side-bar__header__box__name
        -#ログイン中のuser名が表示されるよう、下記コードに変更
        = current_user.name
      .side-bar__header__box__icon
        -#editボタンで新規チャットグループ登録ページ（/groups/new）に遷移するよう、link_to先を変更
        .side-bar__header__box__icon__btn
          = link_to '/groups/new', class: "side-bar__header__box__icon__btn side-bar__header__box__icon__btn--edit" do
            = icon('fas', 'edit',  class: "side-bar__header__box__icon__btn--logo")
        -#cogボタンで編集ページに遷移するよう、link_to先を変更
        .side-bar__header__box__icon__btn
          = link_to edit_user_path(current_user), class: "side-bar__header__box__icon__btn side-bar__header__box__icon__btn--cog" do
            = icon('fas', 'cog',  class: "side-bar__header__box__icon__btn--logo")

  -#応用カリNo91にて、viewの調整でlink_toメソッドでGroup情報を取得しての表示に変更するため、コードを書き換え
  .side-bar__content
    -# .side-bar__content__group
    -#   .side-bar__content__group__name
    -#     グループ001
    -#   .side-bar__content__group__message
    -#     テスト入力001。
    -# .side-bar__content__group
    -#   .side-bar__content__group__name
    -#     グループ002
    -#   .side-bar__content__group__message
    -#     テスト入力002。
    -# .side-bar__content__group
    -#   .side-bar__content__group__name
    -#     グループ003
    -#   .side-bar__content__group__message
    -#     テスト入力003。
    - current_user.groups.each do |chatgroup|
      -#応用カリNo92にて、link_toメソッドのリンク先を下記のとおり書き換え
      -# .side-bar__content__group
      -#   = link_to '#' do
      .side-bar__content__group
        = link_to group_messages_path(chatgroup) do
          .side-bar__content__group__name
            = chatgroup.name
          -#応用カリNo92、最新メッセージの表示機能の実装にて、modelで定義したshow_last_messageメソッドで参照するコードに書き換え
          -# .side-bar__content__group__message
          -#   メッセージはまだありません
          .side-bar__content__group__message
            = chatgroup.show_last_message

app/views/messages/index.html.haml
-#応用カリNo89の実演にて、indexアクションの設定時に生成されたファイル+コード
-#（初期の表示確認以降は不要なのでコメントアウト）
-# %h1 Messages#index
-# %p Find me in app/views/messages/index.html.haml

-#応用No110にて、autoReloadのJSを読み込む下記コードを追記
= javascript_include_tag 'autoReload'

-#応用カリNo89の実演にて、別途作成したHamlファイルを読み込むコードを記述
.wrapper
  = render "side_bar"
  = render "main_chat"

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 Edit Account
    %h5 アカウントの編集
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'Button'
    = link_to "トップページに戻る", :back, class: 'Button'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :name
        .FormField__input--normal
          = f.text_field :name, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      = f.submit "Update", class: 'Button UserButton'